version: '3'
services:
  database:
    env_file:
      - .env
    image: mongo:latest
    restart: always
    container_name: ${MONGO_HOST}
    hostname: ${MONGO_HOST}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./db/data:/data/db
      - ./db/data/log:/var/log/mongodb/
    ports:
      - '27017:${MONGO_PORT}'
    #command: mongod --auth --port 27017
    networks:
      - default

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${WEB_HOST}
    hostname: ${WEB_HOST}
    ports:
      - '8080:${WEB_PORT}'
    links:
      - database
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/lab/backend
    networks:
      - default

  frontend:
    build: ./front/app
    container_name: frontapp_c
    ports:
      - '2000:3000'
    restart: always
    networks:
      - default
    depends_on:
      - backend
    volumes:
      - ./front/app:/usr/src/lab/front/app
      - ./front/app/node_modules:/usr/src/lab/front/app/node_modules
    stdin_open: true
    tty: true
