version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '5002:80'
    volumes:
      - ./backend:/usr/src/lab/backend

  frontend:
    build: ./front/app
    container_name: frontapp_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
