FROM python:3.11

WORKDIR /usr/src/lab/backend

COPY . .

RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt


# Establecer la orden de ejecución predeterminada
CMD ["uvicorn", "main:app", "--reload","--host", "0.0.0.0", "--port", "80"]